# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_generator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_generator.proto',
  package='data_generator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x64\x61ta_generator.proto\x12\x0e\x64\x61ta_generator\"\x1d\n\x05Input\x12\t\n\x01\x64\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\t\"\x1b\n\x0eStringResponse\x12\t\n\x01s\x18\x01 \x01(\t2]\n\x11ServiceDefinition\x12H\n\rGenerateImage\x12\x15.data_generator.Input\x1a\x1e.data_generator.StringResponse\"\x00\x62\x06proto3')
)




_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='data_generator.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='d', full_name='data_generator.Input.d', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='data_generator.Input.k', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=69,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='data_generator.StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='data_generator.StringResponse.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), dict(
  DESCRIPTOR = _INPUT,
  __module__ = 'data_generator_pb2'
  # @@protoc_insertion_point(class_scope:data_generator.Input)
  ))
_sym_db.RegisterMessage(Input)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGRESPONSE,
  __module__ = 'data_generator_pb2'
  # @@protoc_insertion_point(class_scope:data_generator.StringResponse)
  ))
_sym_db.RegisterMessage(StringResponse)



_SERVICEDEFINITION = _descriptor.ServiceDescriptor(
  name='ServiceDefinition',
  full_name='data_generator.ServiceDefinition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=100,
  serialized_end=193,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateImage',
    full_name='data_generator.ServiceDefinition.GenerateImage',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_STRINGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICEDEFINITION)

DESCRIPTOR.services_by_name['ServiceDefinition'] = _SERVICEDEFINITION

# @@protoc_insertion_point(module_scope)
